# Generated by Django 5.0.3 on 2024-03-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_songdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Song', models.FileField(upload_to='songs')),
                ('Name', models.CharField(max_length=255)),
                ('Language', models.CharField(max_length=255)),
                ('Genre', models.CharField(max_length=255)),
                ('Artist', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='SongDb',
        ),
    ]
