# Generated by Django 5.0.3 on 2024-03-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_audiodb_delete_songdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiodb',
            old_name='Song',
            new_name='Audio_File',
        ),
        migrations.RenameField(
            model_name='audiodb',
            old_name='Name',
            new_name='Song_Name',
        ),
    ]
