# Generated by Django 5.0.3 on 2024-03-07 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_song_audiodb_audio_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiodb',
            old_name='Song_Name',
            new_name='Name',
        ),
    ]
