# Generated by Django 5.0.3 on 2024-03-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_audiodb_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genre_Name', models.CharField(max_length=255)),
            ],
        ),
    ]
