# Generated by Django 5.0.3 on 2024-03-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_genredb'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagedb',
            name='Language_Image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='languagedb',
            name='Language_Subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='languagedb',
            name='Language_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
