# Generated by Django 5.0.3 on 2024-03-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_languagedb_language_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagedb',
            name='Language_Subtitle',
            field=models.ImageField(blank=True, null=True, upload_to='language'),
        ),
    ]
