# Generated by Django 5.0.3 on 2024-03-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_languagedb_language_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagedb',
            name='Language_Image',
            field=models.ImageField(blank=True, null=True, upload_to='language'),
        ),
        migrations.AlterField(
            model_name='languagedb',
            name='Language_Subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
