# Generated by Django 5.0.3 on 2024-03-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_languagedb_language_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genredb',
            name='Genre_Image',
            field=models.ImageField(blank=True, null=True, upload_to='genre'),
        ),
        migrations.AddField(
            model_name='genredb',
            name='Genre_Subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='audiodb',
            name='Audio_File',
            field=models.FileField(blank=True, null=True, upload_to='songs'),
        ),
        migrations.AlterField(
            model_name='audiodb',
            name='Genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='audiodb',
            name='Language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='audiodb',
            name='Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='genredb',
            name='Genre_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
