# Generated by Django 5.0.3 on 2024-03-12 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_genredb_genre_image_genredb_genre_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiodb',
            name='Img_File',
            field=models.FileField(blank=True, null=True, upload_to='cover'),
        ),
    ]
