# Generated by Django 5.0.3 on 2024-03-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_audiodb_img_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodb',
            name='Img_File',
            field=models.ImageField(blank=True, null=True, upload_to='cover'),
        ),
    ]
