# Generated by Django 5.0.3 on 2024-03-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_audiodb_img_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiodb',
            name='id',
        ),
        migrations.AddField(
            model_name='audiodb',
            name='Srl_Num',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
    ]
