# Generated by Django 5.0.3 on 2024-03-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_remove_audiodb_id_audiodb_srl_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongsDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Srl_Num', models.IntegerField(blank=True, null=True)),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Language', models.CharField(blank=True, max_length=255, null=True)),
                ('Genre', models.CharField(blank=True, max_length=255, null=True)),
                ('Audio_File', models.FileField(blank=True, null=True, upload_to='songs')),
                ('Img_File', models.ImageField(blank=True, null=True, upload_to='cover')),
            ],
        ),
        migrations.DeleteModel(
            name='AudioDb',
        ),
    ]
