# Generated by Django 5.0.3 on 2024-03-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_songsdb_delete_audiodb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genredb',
            name='Genre_Image',
        ),
    ]
