# Generated by Django 5.0.3 on 2024-03-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_songsdb_artists_songsdb_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='songsdb',
            name='Album_or_Film',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
