# Generated by Django 4.2.4 on 2024-03-18 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_songsdb_album_or_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='genredb',
            name='Genre_Language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
