# Generated by Django 4.2.4 on 2024-03-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_genredb_genre_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='CombinedDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Com_Language', models.CharField(blank=True, max_length=255, null=True)),
                ('Com_Genre', models.CharField(blank=True, max_length=255, null=True)),
                ('Com_Subtitle', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
