# Generated by Django 4.2.4 on 2024-03-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_combineddb'),
    ]

    operations = [
        migrations.AddField(
            model_name='genredb',
            name='Genre_Img_File',
            field=models.ImageField(blank=True, null=True, upload_to='cover'),
        ),
    ]
