# Generated by Django 4.2.4 on 2024-03-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_alter_genredb_genre_img_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genredb',
            name='Genre_Img_File',
        ),
        migrations.AddField(
            model_name='combineddb',
            name='Genre_Img_File',
            field=models.ImageField(blank=True, null=True, upload_to='combine'),
        ),
    ]
