# Generated by Django 4.2.4 on 2024-03-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_remove_genredb_genre_img_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combineddb',
            old_name='Genre_Img_File',
            new_name='Com_Img_File',
        ),
    ]
