# Generated by Django 4.2.4 on 2024-03-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_subgenredb'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCombinedDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_Com_Language', models.CharField(blank=True, max_length=255, null=True)),
                ('Sub_Com_Genre', models.CharField(blank=True, max_length=255, null=True)),
                ('Sub_Com_Subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('Sub_Com_Img_File', models.ImageField(blank=True, null=True, upload_to='subcomb')),
            ],
        ),
    ]
