# Generated by Django 4.2.4 on 2024-03-19 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_rename_sub_com_language_subcombineddb_sub_com_subgenre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcombineddb',
            old_name='Sub_Com_SubGenre',
            new_name='Sub_Com_Res_SubGenre',
        ),
        migrations.RemoveField(
            model_name='combineddb',
            name='Com_Subtitle',
        ),
        migrations.RemoveField(
            model_name='subcombineddb',
            name='Sub_Com_Subtitle',
        ),
    ]
