# Generated by Django 4.2.4 on 2024-03-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_combineddb_com_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genredb',
            name='Genre_Language',
        ),
        migrations.RemoveField(
            model_name='genredb',
            name='Genre_Subtitle',
        ),
    ]
