# Generated by Django 4.2.4 on 2024-03-22 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_remove_genredb_genre_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combineddb',
            name='Com_Subtitle',
        ),
        migrations.RemoveField(
            model_name='subcombineddb',
            name='Sub_Com_Subtitle',
        ),
        migrations.RemoveField(
            model_name='subgenredb',
            name='Sub_Genre_Sbtl',
        ),
    ]
