# Generated by Django 4.2.4 on 2024-04-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_rename_genre_genredb_genrename_genredb_genreimg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subgenredb',
            old_name='Res_Sub_Genre',
            new_name='GenreName',
        ),
        migrations.RenameField(
            model_name='subgenredb',
            old_name='SubGenre_Name',
            new_name='SubName',
        ),
        migrations.AddField(
            model_name='subgenredb',
            name='SubImg',
            field=models.ImageField(blank=True, null=True, upload_to='genre'),
        ),
    ]
