# Generated by Django 4.2.4 on 2024-04-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_rename_res_sub_genre_subgenredb_genrename_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songsdb',
            old_name='Album_or_Film',
            new_name='Album_Film',
        ),
        migrations.RenameField(
            model_name='songsdb',
            old_name='Audio_File',
            new_name='AudioFile',
        ),
        migrations.RenameField(
            model_name='songsdb',
            old_name='Img_File',
            new_name='ImgFile',
        ),
        migrations.RenameField(
            model_name='songsdb',
            old_name='Srl_Num',
            new_name='No',
        ),
        migrations.RenameField(
            model_name='songsdb',
            old_name='Sub_Genre',
            new_name='Type',
        ),
    ]
