# Generated by Django 4.2.4 on 2024-04-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_rename_album_or_film_songsdb_album_film_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songsdb',
            old_name='Artists',
            new_name='Artist',
        ),
        migrations.RenameField(
            model_name='songsdb',
            old_name='AudioFile',
            new_name='Audio',
        ),
        migrations.RenameField(
            model_name='songsdb',
            old_name='ImgFile',
            new_name='Image',
        ),
    ]
