# Generated by Django 4.2.4 on 2024-04-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_rename_artists_songsdb_artist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songsdb',
            old_name='Album_Film',
            new_name='Film',
        ),
    ]
