# Generated by Django 4.2.4 on 2024-04-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_rename_album_film_songsdb_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='songsdb',
            name='Extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
