# Generated by Django 4.2.4 on 2024-03-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Username', models.CharField(blank=True, max_length=255, null=True)),
                ('Password', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
