# Generated by Django 4.2.4 on 2024-04-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_usersdb_mob_no_usersdb_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistsDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Username', models.CharField(blank=True, max_length=255, null=True)),
                ('Audio', models.FileField(blank=True, null=True, upload_to='playlists')),
            ],
        ),
    ]
