# Generated by Django 4.2.4 on 2024-04-01 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_playlistsdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlistsdb',
            old_name='Name',
            new_name='AudName',
        ),
        migrations.RemoveField(
            model_name='playlistsdb',
            name='Audio',
        ),
    ]
