# Generated by Django 4.2.4 on 2024-04-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_rename_audname_playlistsdb_songname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistsdb',
            name='ArtistName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
