# Generated by Django 4.2.4 on 2024-04-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_alter_usersdb_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdb',
            name='Profile',
            field=models.ImageField(blank=True, default='{% static "img/nouser.jpg" %}', null=True, upload_to='profile'),
        ),
    ]
