# Generated by Django 4.2.4 on 2024-04-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_rename_playlistsdb_likedsongs'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(blank=True, max_length=255, null=True)),
                ('PlaylistName', models.CharField(blank=True, max_length=255, null=True)),
                ('SongName', models.CharField(blank=True, max_length=255, null=True)),
                ('Image', models.ImageField(blank=True, default='added', null=True, upload_to='added')),
            ],
        ),
    ]
