# Generated by Django 4.2.4 on 2024-04-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_addsongs'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedsongs',
            name='PlaylistName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
